-- ============================================================================
-- Migration: COMPARE_OP Phase 1 — reflected op in py_object_richcompare
-- Created: 2026-01-14 24:00:00
--
-- py_object_richcompare (with reflected op) is defined in 20260114236000_tp_richcompare_slot.sql.
-- Design: docs/COMPARE_OP_IMPLEMENTATION_PLAN.md
-- ============================================================================
